par: Compilepar+Linkpar Executepar
unpar: Compile Link Execute

Compile:
		g++ -c -std=c++11 project4.cpp -larmadillo

Link:
		g++ -std=c++11 project4.o -o project4.exe  -larmadillo

Execute:
		./project4.exe


Compilepar+Linkpar:
		g++ project4.cpp -std=c++11 -larmadillo -llapack -lblas -fopenmp -o project4.out

Executepar:
		./project4.out
